openapi: 3.0.0
paths:
  /health-check:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
  /api/auth/sign-up:
    post:
      operationId: AuthController_signUp
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: ''
      tags: &ref_0
        - Auth
  /api/auth/sign-in:
    post:
      operationId: AuthController_signIn
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInDto'
      responses:
        '200':
          description: ''
      tags: *ref_0
  /api/auth/refresh-access:
    post:
      operationId: AuthController_refreshAccess
      parameters: []
      responses:
        '201':
          description: ''
      tags: *ref_0
  /api/auth/logout:
    post:
      operationId: AuthController_logout
      parameters: []
      responses:
        '201':
          description: ''
      tags: *ref_0
  /api/auth/confirm-email:
    post:
      operationId: AuthController_confirmEmail
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmEmailDto'
      responses:
        '201':
          description: ''
      tags: *ref_0
  /api/auth/forgot-password:
    post:
      operationId: AuthController_forgotPassword
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailDto'
      responses:
        '200':
          description: ''
      tags: *ref_0
  /api/auth/update-password:
    patch:
      operationId: AuthController_updatePassword
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordDto'
      responses:
        '200':
          description: ''
      tags: *ref_0
  /api/auth/me:
    get:
      operationId: AuthController_getMe
      parameters: []
      responses:
        '200':
          description: ''
      tags: *ref_0
  /user/sign-up:
    post:
      operationId: UserController_signUp
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: ''
  /user/sign-in:
    post:
      operationId: UserController_signIn
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: ''
  /user/verify-otp:
    post:
      operationId: UserController_verifyOtp
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OtpRequestDto'
      responses:
        '201':
          description: ''
  /user/reset-password:
    put:
      operationId: UserController_resetPassword
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordDto'
      responses:
        '200':
          description: ''
  /user/send-otp/{email}:
    get:
      operationId: UserController_emailSend
      parameters:
        - name: email
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /user:
    get:
      operationId: UserController_findAll
      parameters: []
      responses:
        '200':
          description: ''
  /user/{uuid}:
    get:
      operationId: UserController_findOne
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
    delete:
      operationId: UserController_remove
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /venue:
    post:
      operationId: VenueController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateVenueDto'
      responses:
        '201':
          description: ''
    get:
      operationId: VenueController_findAll
      parameters: []
      responses:
        '200':
          description: ''
  /venue/{id}:
    get:
      operationId: VenueController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
    patch:
      operationId: VenueController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateVenueDto'
      responses:
        '200':
          description: ''
    delete:
      operationId: VenueController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /event/sse:
    get:
      operationId: ServerSentEventController_sse
      parameters: []
      responses:
        '200':
          description: ''
  /social-media:
    post:
      operationId: SocialMediaController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSocialMediaDto'
      responses:
        '201':
          description: ''
  /location:
    post:
      operationId: LocationController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationDto'
      responses:
        '200':
          description: ''
  /location/venue/{venueOperatorId}:
    get:
      operationId: LocationController_get
      parameters:
        - name: venueOperatorId
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /location/{id}:
    get:
      operationId: LocationController_getById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
info:
  title: API
  description: API docs
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    JWT:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    CreateUserDto:
      type: object
      properties: {}
    SignInDto:
      type: object
      properties:
        email:
          type: string
          description: Username or email
          examples:
            - john.doe
            - john.doe@gmail.com
          minLength: 3
          maxLength: 255
        password:
          type: string
          description: User's password
          minLength: 1
      required:
        - email
        - password
    ConfirmEmailDto:
      type: object
      properties:
        confirmationToken:
          type: string
          description: The JWT token sent to the user email
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      required:
        - confirmationToken
    EmailDto:
      type: object
      properties:
        email:
          type: string
          description: The email of the user
          example: someone@gmail.com
          minLength: 5
          maxLength: 255
      required:
        - email
    ChangePasswordDto:
      type: object
      properties:
        password1:
          type: string
          description: New password
          minLength: 8
          maxLength: 35
        password2:
          type: string
          description: Password confirmation
          minLength: 1
        password:
          type: string
          description: The current password
          minLength: 1
      required:
        - password1
        - password2
        - password
    OtpRequestDto:
      type: object
      properties: {}
    ResetPasswordDto:
      type: object
      properties: {}
    CreateVenueDto:
      type: object
      properties: {}
    UpdateVenueDto:
      type: object
      properties: {}
    CreateSocialMediaDto:
      type: object
      properties: {}
    LocationDto:
      type: object
      properties: {}
